- name: Install Azure Cli
  hosts: localhost
  gather_facts: true
  become: true
  tasks:
      - block: #Install az cli on Debian/Ubuntu
      - name: Run MS install script
        shell: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: Install Azure CLi
      package:
        name: "azure-cli"
        state: present

    - name: Verify installed version
      shell: az --version
      register: azureVersion

    - debug:
        msg: "{{azureVersion.stdout}}" 