---
- hosts: localhost
  vars:
    azure_config_dir: "/tmp/{{ tower_workflow_job_id }}"
    
    tasks:
       hosts: localhost
       name: use az login
       shell: az login --service-principal --username {{ CLIENT_ID }} --password {{ SECRET }} --tenant {{ TENANT }}