---

- name: Login to Azure CLU as User account 
  hosts: localhost
  vars:
    azure_config_dir: "/tmp/{{ tower_workflow_job_id }}"
  environment:
    AZURE_CONFIG_DIR: "{{ azure_config_dir }}"
  
  pre_tasks:
    - name: Verify az cli config directory is present 
      file: 
        path: "{{ azure_config_dir }}"
        state: directory
  
  tasks:
  
    - name: Clear any existing login 
      shell: az account clear 
     
    - name: Use Azure Service Principal to sign in
      shell: az login --service-principal --username {{ AZURE_CLIENT_ID }} --password {{ AZURE_SECERT_ID }} --tenant {{ AZURE_TENANT_ID }}